linters:
  enable:
  - asasalint
  - asciicheck
  - bidichk
  - bodyclose
  - containedctx
  - contextcheck
  - decorder
  - dogsled
  - dupword
  - durationcheck
  - errcheck
  - errchkjson
  - errname
  - errorlint
  - execinquery
  - exhaustive
  - exportloopref
  - forbidigo
  - forcetypeassert
  - gci
  - gocheckcompilerdirectives
  - gochecknoinits
  - goconst
  - gocritic
  - godot
  - goerr113
  - gofmt
  - gofumpt
  - goimports
  - gomodguard
  - goprintffuncname
  - gosec
  - gosimple
  - gosmopolitan
  - govet
  - grouper
  - importas
  - ineffassign
  - interfacebloat
  - ireturn
  - loggercheck
  - mirror
  - misspell
  - musttag
  - nakedret
  - nilerr
  - nilnil
  - noctx
  - nolintlint
  - nosprintfhostport
  - prealloc
  - predeclared
  - promlinter
  - reassign
  - rowserrcheck
  - sqlclosecheck
  - staticcheck
  - stylecheck
  - tagalign
  - tagliatelle
  - tenv
  - testableexamples
  - testpackage
  - thelper
  - typecheck
  - unconvert
  - unparam
  - unused
  - usestdlibvars
  - wastedassign
  - whitespace
  disable:
  - cyclop
  - depguard
  - dupl
  - exhaustivestruct
  - exhaustruct
  - funlen
  - ginkgolinter
  - gochecknoglobals
  - gocognit
  - gocyclo
  - godox
  - goheader
  - gomnd
  - gomoddirectives
  - lll
  - maintidx
  - makezero
  - nestif
  - nlreturn
  - nonamedreturns
  - paralleltest
  - revive
  - tparallel
  - varnamelen
  - wrapcheck
  - wsl
  - zerologlint

linters-settings:
  gci:
    sections:
    - standard
    - default
    - prefix(github.com/twpayne/go-geos)
  goimports:
    local-prefixes: github.com/twpayne/go-geos

issues:
  exclude-rules:
  - linters:
    - goerr113
    text: "do not define dynamic errors, use wrapped static errors instead"
