name: main
on:
  pull_request:
  push:
    branches:
    - master
    tags:
    - v*
jobs:
  main:
    strategy:
      fail-fast: false
      matrix:
        go-version:
        - 1.x
        - 1.18.x
        os:
        - ubuntu-20.04
        - ubuntu-22.04
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get install -y libgeos-dev
    - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
    - uses: actions/cache@4723a57e26efda3a62cbde1812113b730952852d
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Generate
      run: |
        go generate ./...
        git diff --exit-code
    - name: Build
      run: go build ./...
    - name: Test
      run: go test -race ./...
  lint:
    runs-on: ubuntu-22.04
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get install -y libgeos-dev
    - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
      with:
        go-version: 1.x
    - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
    - uses: golangci/golangci-lint-action@0ad9a0988b3973e851ab0a07adf248ec2e100376
      with:
        version: v1.50.1