name: main
on:
  pull_request:
  push:
    branches:
    - master
    tags:
    - v*
jobs:
  main:
    runs-on: ubuntu-18.04
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get install -y libgeos-dev pkg-config
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.x
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: go build ./...
    - name: Test
      run: go test -race -v ./...
    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.39.0
