name: main
on:
  pull_request:
  push:
    branches:
    - master
    tags:
    - v*
jobs:
  main:
    runs-on: ubuntu-18.04
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get install -y libgeos-dev
    - uses: actions/setup-go@v2
      with:
        go-version: 1.x
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Build
      run: go build ./...
    - name: Test
      run: go test -race -v ./...
  lint:
    runs-on: ubuntu-18.04
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get install -y libgeos-dev
    - uses: actions/setup-go@v2
      with:
        go-version: 1.x
    - uses: actions/checkout@v3
    - uses: golangci/golangci-lint-action@v3.1.0
      with:
        version: v1.45.2

